export const Gminy: string[] = [
    'Bochnia',
    'Bochnia',
    'Lipnica Murowana',
    'Łapanów',
    'Nowy Wiśnicz',
    'Rzezawa',
    'Trzciana',
    'Żegocina',
    'Borzęcin',
    'Brzesko',
    'Czchów',
    'Dębno',
    'Gnojnik',
    'Iwkowa',
    'Szczurowa',
    'Babice',
    'Chrzanów',
    'Libiąż',
    'Trzebinia',
    'Bolesław',
    'Niedzwiedz',
    'Słopnice',
    'Tymbark',
    'Dąbrowa Tarnowska',
    'Gręboszów',
    'Mędrzechów',
    'Olesno',
    'Radgoszcz',
    'Szczucin',
    'Gorlice',
    'Biecz',
    'Bobowa',
    'Gorlice',
    'Lipinki',
    'Łużna',
    'Moszczenica',
    'Ropa',
    'Sękowa',
    'Uście Gorlickie',
    'Czernichów',
    'Igołomia-Wawrzeńczyce',
    'Iwanowice',
    'Charsznica',
    'Gołcza',
    'Kozłów',
    'Jerzmanowice-Przeginia',
    'Kocmyrzów-Luborzyca',
    'Krzeszowice',
    'Liszki',
    'Michałowice',
    'Mogilany',
    'Skała',
    'Skawina',
    'Słomniki',
    'Sułoszowa',
    'Swiatniki Górne',
    'Wielka Wies',
    'Zabierzów',
    'Zielonki',
    'Limanowa',
    'Mszana Dolna',
    'Dobra',
    'Jodłownik',
    'Kamienica',
    'Laskowa',
    'Limanowa',
    'Łukowica',
    'Mszana Dolna',
    'Książ Wielki',
    'Miechów',
    'Racławice',
    'Słaboszów',
    'Dobczyce',
    'Lubień',
    'Myślenice',
    'Pcim',
    'Raciechowice',
    'Siepraw',
    'Sułkowice',
    'Tokarnia',
    'Wiśniowa',
    'Grybów',
    'Chełmiec',
    'Gródek nad Dunajcem',
    'Grybów',
    'Kamionka Wielka',
    'Korzenna',
    'Krynica-Zdrój',
    'Kraków',
    'Łabowa',
    'Łacko',
    'Muszyna',
    'Łososina Dolna',
    'Nawojowa',
    'Piwniczna-Zdrój',
    'Podegrodzie',
    'Rytro',
    'Stary Sącz',
    'Nowy Targ',
    'Szczawnica',
    'Czarny Dunajec',
    'Lipnica Wielka',
    'Jabłonka',
    'Kroscienko nad Dunajcem',
    'Łapsze Niżne',
    'Nowy Targ',
    'Ochotnica Dolna',
    'Raba Wyżna',
    'Rabka-Zdrój',
    'Spytkowice',
    'Szaflary',
    'Bukowno',
    'Bolesław',
    'Klucze',
    'Olkusz',
    'Trzyciaż',
    'Wolbrom',
    'Oswięcim',
    'Chełmek',
    'Kęty',
    'Osiek',
    'Oswięcim',
    'Polanka Wielka',
    'Przeciszów',
    'Zator',
    'Koniusza',
    'Koszyce',
    'Nowe Brzesko',
    'Pałecznica',
    'Proszowice',
    'Radziemice',
    'Jordanów',
    'Budzów',
    'Bystra-Sidzina',
    'Jordanów',
    'Sucha Beskidzka',
    'Maków Podhalański',
    'Stryszawa',
    'Zawoja',
    'Zembrzyce',
    'Ciężkowice',
    'Gromnik',
    'Lisia Góra',
    'Pleśna',
    'Radłów',
    'Ryglice',
    'Rzepiennik Strzyżewski',
    'Skrzyszów',
    'Tarnów',
    'Tuchów',
    'Wierzchosławice',
    'Wietrzychowice',
    'Wojnicz',
    'Zakliczyn',
    'Żabno',
    'Zakopane',
    'Biały Dunajec',
    'Bukowina Tatrzańska',
    'Koscielisko',
    'Poronin',
    'Andrychów',
    'Brzeźnica',
    'Kalwaria Zebrzydowska',
    'Lanckorona',
    'Mucharz',
    'Spytkowice',
    'Stryszów',
    'Tomice',
    'Wadowice',
    'Wieprz',
    'Biskupice',
    'Gdów',
    'Kłaj',
    'Niepołomice',
    'Wieliczka',
    'Drwinia',
    'Brzeszcze',
    'Szerzyny',
    'Czorsztyn',
    'Alwernia',
]